######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 27 00:56:56 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . UI Packages/Robot
INCLUDEPATH += . Packages/Robot

# Input
#HEADERS += Packages/Robot/Robot.h
FORMS += UI/RobotQt.ui
SOURCES += main.cpp #Packages/Robot/Robot.cpp
