######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 23 23:16:04 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . UI Packages/Robot
INCLUDEPATH += .

# Input
HEADERS += Packages/Robot/Robot.h
FORMS += UI/RobotQt.ui
SOURCES += main.cpp Packages/Robot/Robot.cpp
