######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 15 20:52:53 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . UI
INCLUDEPATH += .

# Input
FORMS += UI/RobotQt.ui
SOURCES += RobotQt.cpp
